import type { Locale } from '~/site.config';

/**
 * Open Graph card naming.
 *
 * Cards are generated by src/pages/og/[name].png.ts, whose getStaticPaths
 * iterates the same route registry the sitemap uses. Because both sides derive
 * the filename from `ogName`, a page can never reference a card that was not
 * generated — there is nothing to keep in sync by hand.
 */

/** `('courses/ai-for-business', 'ar')` → `'ar-courses-ai-for-business'` */
export function ogName(key: string, lang: Locale): string {
  const slug = key.replace(/^\/+|\/+$/g, '').replace(/\//g, '-') || 'home';
  return `${lang}-${slug}`;
}

/** Public path of the card for a route, relative to the site base. */
export function ogImagePath(key: string, lang: Locale): string {
  return `og/${ogName(key, lang)}.png`;
}
